-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["Bubble"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "Bubble", density = 2, friction = 0.6, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    radius = 144.003
                    }
                    
                    
		}
		
		, 
		["Bubble_Reduced"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "Bubble_Reduced", density = 2, friction = 0.6, bounce = 1, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    radius = 107.005
                    }
                    
                    
		}
		
		, 
		["BubbleShield"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "BubbleShield", density = 2, friction = 0, bounce = 1, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    radius = 245.000
                    }
                    
                    
		}
		
		, 
		["Planet"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "Planet", density = 2, friction = 0.6, bounce = 1, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    radius = 148.000
                    }
                    
                    
		}
		
		, 
		["Planet_Reduced"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "Planet_Reduced", density = 2, friction = 0.6, bounce = 1, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    radius = 114.000
                    }

                    
                    
		}
		
		, 
		["PlanetShield"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "PlanetShield", density = 2, friction = 0.6, bounce = 1, 
                    filter = { categoryBits = 32, maskBits = 65535, groupIndex = 0 },
                    radius = 247.000
                    }
                    
                    
		}
        ,
        ["Pin1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "Pin1", density = 0.3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   -65, 25  ,  -33, 3  ,  -9, 29  ,  -30, 61  }
                    }
                     ,
                    {
                    pe_fixture_id = "Pin1", density = 0.3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   -9, 29  ,  -33, 3  ,  -16, -41  ,  10, -24  ,  21, -10  ,  40, 17  }
                    }
                     ,
                    {
                    pe_fixture_id = "Pin1", density = 0.3, friction = 0, bounce = 0, 
                    filter = { categoryBits = 4, maskBits = 65535, groupIndex = 0 },
                    shape = {   21, -10  ,  10, -24  ,  66, -67  }
                    }
                    
                    
                    
        }
        
        , 
        ["Shu1"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "Shu1", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 16, maskBits = 65535, groupIndex = 0 },
                    shape = {   15, 28  ,  -30, 17  ,  -72, -2  ,  -22, -19  ,  34, -15  ,  69, 4  }
                    }
                     ,
                    {
                    pe_fixture_id = "Shu1", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 16, maskBits = 65535, groupIndex = 0 },
                    shape = {   -15, 43  ,  15, 28  ,  -5, 73  }
                    }
                     ,
                    {
                    pe_fixture_id = "Shu1", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 16, maskBits = 65535, groupIndex = 0 },
                    shape = {   -30, 17  ,  15, 28  ,  -15, 43  }
                    }
                     ,
                    {
                    pe_fixture_id = "Shu1", density =0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 16, maskBits = 65535, groupIndex = 0 },
                    shape = {   13, -34  ,  -12, -34  ,  1, -72  }
                    }
                     ,
                    {
                    pe_fixture_id = "Shu1", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 16, maskBits = 65535, groupIndex = 0 },
                    shape = {   -22, -19  ,  -12, -34  ,  13, -34  ,  34, -15  }
                    }
                    
                    
                    
        }
        
        , 
        ["Shu2"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "Shu2", density = 0.2, friction = 0, bounce = 1, 
                    filter = { categoryBits = 32, maskBits = 65535, groupIndex = 0 },
                    shape = {   -40, -71  ,  11, -49  ,  -42, -46  ,  -65, -66  }
                    }
                     ,
                    {
                    pe_fixture_id = "Shu2", density = 0.2, friction = 0, bounce = 1, 
                    filter = { categoryBits = 32, maskBits = 65535, groupIndex = 0 },
                    shape = {   60, -21  ,  42, 7  ,  31, -36  ,  63, -62  }
                    }
                     ,
                    {
                    pe_fixture_id = "Shu2", density = 0.2, friction = 0, bounce = 1, 
                    filter = { categoryBits = 32, maskBits = 65535, groupIndex = 0 },
                    shape = {   -56, -1  ,  -36, -25  ,  -30, 23  ,  -65, 52  }
                    }
                     ,
                    {
                    pe_fixture_id = "Shu2", density = 0.2, friction = 0, bounce = 1, 
                    filter = { categoryBits = 32, maskBits = 65535, groupIndex = 0 },
                    shape = {   6, 54  ,  -30, 23  ,  -36, -25  ,  36, 33  ,  61, 58  }
                    }
                     ,
                    {
                    pe_fixture_id = "Shu2", density = 0.2, friction = 0, bounce = 1, 
                    filter = { categoryBits = 32, maskBits = 65535, groupIndex = 0 },
                    shape = {   11, -49  ,  31, -36  ,  42, 7  ,  36, 33  ,  -36, -25  ,  -42, -46  }
                    }
                    
                    
                    
        }
        
        , 
        ["UFO"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "UFO", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 64, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25.5, 26.5  ,  -14.5, 23.5  ,  -13.5, 47.5  ,  -26.5, 53.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "UFO", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 64, maskBits = 65535, groupIndex = 0 },
                    shape = {   11.5, 42.5  ,  6.5, 17.5  ,  16.5, 13.5  ,  26.5, 41.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "UFO", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 64, maskBits = 65535, groupIndex = 0 },
                    shape = {   -4.5, -57.5  ,  16.5, -42.5  ,  43.5, 1.5  ,  -25.5, 26.5  ,  -38.5, -21.5  ,  -28.5, -51.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "UFO", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 64, maskBits = 65535, groupIndex = 0 },
                    shape = {   -67.5, 5.5  ,  -38.5, -21.5  ,  -25.5, 26.5  ,  -62.5, 22.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "UFO", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 64, maskBits = 65535, groupIndex = 0 },
                    shape = {   67.5, -24.5  ,  43.5, 1.5  ,  16.5, -42.5  ,  27.5, -45.5  ,  51.5, -45.5  ,  62.5, -40.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "UFO", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 64, maskBits = 65535, groupIndex = 0 },
                    shape = {   57.5, 25.5  ,  51.5, 27.5  ,  35.5, 4.5  ,  43.5, 1.5  ,  61.5, 16.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "UFO", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 64, maskBits = 65535, groupIndex = 0 },
                    shape = {   -25.5, 26.5  ,  35.5, 4.5  ,  16.5, 13.5  ,  6.5, 17.5  }
                    }
                    
                    
                    
        }
        
        , 
        ["Satellite"] = {
                    
                    
                    
                    
                    {
                    pe_fixture_id = "Satellite", density = 0.4, friction = 0, bounce = 1, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   -44.5, 21.5  ,  -23.5, -8.5  ,  -4.5, -25.5  ,  17.5, -13.5  ,  5.5, 11.5  ,  -14.5, 46.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Satellite", density = 0.4, friction = 0, bounce = 1, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   17.5, -13.5  ,  -4.5, -25.5  ,  10.5, -44.5  ,  31.5, -30.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Satellite", density = 0.4, friction = 0, bounce = 1, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   5.5, 11.5  ,  17.5, -13.5  ,  66.5, 21.5  ,  51.5, 41.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "Satellite", density = 0.4, friction = 0, bounce = 1, 
                    filter = { categoryBits = 8, maskBits = 65535, groupIndex = 0 },
                    shape = {   -64.5, -41.5  ,  -57.5, -58.5  ,  -4.5, -25.5  ,  -23.5, -8.5  }
                    }
                    
                    
                    
        }
        
        , 
        ["Object"] = {
                    
                    
                    
                    {
                    pe_fixture_id = "Object", density = 0.3, friction = 0, bounce = 1, 
                    filter = { categoryBits = 2, maskBits = 65535, groupIndex = 0 },
                    radius = 61.008
                    }
                    
                    
        }
        

        ,
		
}}

    local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
    
    function physics:get(name)
        return unpack(self.data[name])
    end

    function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
    end
	
	return physics;
end

return M

